# Generated by Django 3.1.4 on 2020-12-22 02:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('maxPeople', models.IntegerField()),
                ('compensation', models.TextField(max_length=250)),
                ('zipcode', models.CharField(default=12345, max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(default='Enter your bio here!', max_length=255)),
                ('zipcode', models.CharField(default=12345, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('1', 'Cleaning'), ('2', 'Gardening'), ('3', 'Electrical'), ('4', 'Babysitting'), ('5', 'Pest Control'), ('6', 'DJing'), ('7', 'General Labor'), ('8', 'Handyperson'), ('9', 'Computer Skills'), ('10', 'Auto Mechanic'), ('11', 'Carpentry'), ('12', 'Power Tools'), ('13', 'Organizer'), ('14', 'Music Teaching'), ('15', 'Animal Handling'), ('16', 'Photography'), ('17', 'Writing'), ('18', 'Art'), ('19', 'Doomsday Prepping'), ('20', 'Cooking'), ('21', 'Sewing'), ('22', 'Plumbing'), ('23', 'Welding'), ('24', 'Quantum Physics'), ('25', 'Intimidation')], default='1', max_length=2)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobapplicationmap',
            constraint=models.UniqueConstraint(fields=('user_id', 'jobPost_id'), name='user_id_job_post_id_unique'),
        ),
    ]
