# Generated by Django 3.1.4 on 2020-12-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='competnsation',
            new_name='compensation',
        ),
    ]
