# Generated by Django 3.1.4 on 2020-12-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='value',
            new_name='name',
        ),
    ]
