# Generated by Django 3.1.2 on 2020-12-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplicationmap',
            name='useri_id_job_post_id_unique',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='zipcode',
            field=models.CharField(default=12345, max_length=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('1', 'Cleaning'), ('2', 'Gardening'), ('3', 'Electrical'), ('4', 'Babysitting'), ('5', 'Pest Control'), ('6', 'DJing'), ('7', 'General Labor'), ('8', 'Handyperson'), ('9', 'Computer Skills'), ('10', 'Auto Mechanic'), ('11', 'Carpentry'), ('12', 'Power Tools'), ('13', 'Organizer'), ('14', 'Music Teaching'), ('15', 'Animal Handling'), ('16', 'Photography'), ('17', 'Writing'), ('18', 'Art'), ('19', 'Doomsday Prepping'), ('20', 'Cooking'), ('21', 'Sewing'), ('22', 'Plumbing'), ('23', 'Welding'), ('24', 'Quantum Physics'), ('25', 'Intimidation')], default='1', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='jobapplicationmap',
            constraint=models.UniqueConstraint(fields=('user_id', 'jobPost_id'), name='user_id_job_post_id_unique'),
        ),
    ]
