# Generated by Django 3.1.4 on 2020-12-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201218_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
