# Generated by Django 3.1.2 on 2020-12-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201221_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('C', 'Cleaning'), ('G', 'Gardening'), ('E', 'Electrical'), ('B', 'Babysitting'), ('P', 'Pest Control'), ('D', 'DJing'), ('L', 'General Labor'), ('H', 'Handyperson'), ('S', 'Computer Skills')], default='C', max_length=1),
        ),
    ]
