# Generated by Django 3.1.4 on 2020-12-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.zip_code'),
        ),
    ]
