# Generated by Django 3.1.4 on 2020-12-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201218_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zip_Code',
            new_name='ZipCode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='zipcode',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
