# Generated by Django 3.1.4 on 2020-12-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_jobpost_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('1', 'Cleaning'), ('2', 'Gardening'), ('3', 'Electrical'), ('4', 'Babysitting'), ('5', 'Pest Control'), ('6', 'DJing'), ('7', 'General Labor'), ('8', 'Handyperson'), ('9', 'Computer Skills'), ('10', 'Auto Mechanic'), ('11', 'Carpentry'), ('12', 'Power Tools'), ('13', 'Organizer'), ('14', 'Music Teaching'), ('15', 'Animal Handling'), ('16', 'Photography'), ('17', 'Writing'), ('18', 'Art'), ('19', 'Doomsday Prepping'), ('20', 'Cooking'), ('21', 'Sewing'), ('22', 'Plumbing'), ('23', 'Welding'), ('24', 'Quantum Physics'), ('25', 'Intimidation')], default='1', max_length=2),
        ),
    ]
