# Generated by Django 3.1.4 on 2020-12-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201218_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.zipcode'),
        ),
    ]
