# Generated by Django 3.1.4 on 2020-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201218_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.ManyToManyField(to='main_app.ZipCode'),
        ),
    ]
